version: '3.8'

services:
  feedsync:
    container_name: feedsync
    image:  ghcr.io/tunsworthy/feedsync:latest
    env_file:
      - .env
    networks:
     - baby_org_net
     - bridge  
networks:
  
  baby_org_net:
    name: baby_org_net
    internal: true
  bridge:
    external: true  # use Docker's default bridge network for internet
